# Generated by Django 4.0.4 on 2022-04-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_softwareinstance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareinstance',
            name='license_key',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
    ]
