# Generated by Django 4.0.4 on 2022-04-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_softwareinstance_license_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'permissions': (('can_make', 'Can add a software'),)},
        ),
    ]
