# Generated by Django 4.0.4 on 2022-04-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_software_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'permissions': (('can_make', 'Can add a software from front'),)},
        ),
    ]
