# Generated by Django 4.0.4 on 2022-04-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_software_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
    ]
