# Generated by Django 4.0.4 on 2022-04-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_software_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'permissions': (('can_make', 'Abiity to add a software'),)},
        ),
    ]
