# Generated by Django 4.0.4 on 2022-04-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_alter_softwareinstance_software_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestingSoftware',
            fields=[
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('reason', models.TextField(help_text='Enter a reason for why you need the software', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this software instance', primary_key=True, serialize=False)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.software')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['send_date'],
            },
        ),
    ]
