# Generated by Django 4.0.4 on 2022-04-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_requestingsoftware'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestingsoftware',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='requestingsoftware',
            name='lastname',
        ),
    ]
