# Generated by Django 4.0.4 on 2022-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rename_firstname_requestingsoftware_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareinstance',
            name='renewal_cost',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
