# Generated by Django 4.0.4 on 2022-04-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_softwareinstance_renewal_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unailable')], default='a', help_text='Book availability', max_length=1),
        ),
    ]
